const fellowsData = [
    {
        id: "1",
        name: "Dr. David W. Dodick",
        title: "Chief Science Officer & Chair, Neurology",
        paragraph1: "Chief Science Officer & Chair, Atria Academy of Science & Medicine",
        paragraph2: "Dr. Dodick is Emeritus Professor of Neurology at the Mayo Clinic, where he founded and directed the Headache and Sport Neurology and Concussion Programs at Mayo Clinic in Arizona. He is a Mayo Clinic Distinguished Investigator and Distinguished Educator. He has authored more than 900 peer-reviewed manuscripts and abstracts and authored or edited 13 books. He is the Chair of the American Brain Foundation and Chair of the IHS Global Patient Advocacy Coalition. He is the Immediate Past-Chair of the American Migraine Foundation, former Editor of Cephalalgia, a Past-President of both the American Headache Society and the International Headache Society.",
        paragraph3: "He is Professor Emeritus at the Mayo Clinic, a consultant for Mayo Clinic International, and an Adjunct Professor at the Norwegian University of Science and Technology and the University of Copenhagen.",
        paragraph4: "Co-Chair at Atria Academy of Science & Medicine",
        paragraph5: "Chief Science Officer at Atria",
        paragraph6: "Professor Emeritus of Neurology at Mayo Clinic",
        paragraph7: "Chair at American Brain Foundation"
    },
    {
        id: "2",
        name: "Dr. Cheryl Pegus",
        title: "Co-Chair, Cardiology",
        paragraph1: "Dr. Pegus is Walmart's executive vice president of Health & Wellness. She joins Walmart from Cambia Health Solutions where she was President of Consumer Health Solutions and Chief Medical Officer. After working in private practice for several years as a cardiologist, Dr. Pegus joined Pfizer where she focused on the development of clinical protocols and early disease management programs. She also served at Aetna, where her work focused on wellness, women's health, health equity, and predictive analytics. Additionally, Dr. Pegus is co-founder of A New Beat, an organization dedicated to improving the cardiovascular health and careers of women and underrepresented minorities.",
        paragraph2: "Co-Chair at Atria Academy of Science & Medicine",
        paragraph3: "Executive Vice President at Health and Wellness at Walmart",
        paragraph4: "Director and Immediate Past Board Chair at Association of Black Cardiologists",
        paragraph5: "Director at American Heart Association",
        paragraph6: "Co-Founder at A New Beat",
        paragraph7: ""
    },
    {
        id: "3",
        name: "Dr. Gregory Poland",
        title: "Co-Chair, Vaccines",
        paragraph1: "Dr. Poland is a physician-scientist and the founding and current director of Mayo Clinic's Vaccine Research Group — a state-of-the-art research group and laboratory that seeks to understand genetic drivers of viral vaccine response and application of systems biology approaches to the generation of immunity, as well as the development of novel vaccines against emerging pathogens important to public health. The Poland lab developed the field of viral vaccine immunogenetics, the immune response network theory, and the field of vaccinomics and adversomics. Dr. Poland has given over 2,700 national and international media interviews and professional presentations on the COVID-19 pandemic and vaccines.",
        paragraph2: "Mary Lowell Leary Emeritus Professor of Medicine at the Mayo Clinic College of Medicine",
        paragraph3: "Distinguished Investigator at the Mayo Clinic",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "4",
        name: "Dr. Marc E. Agronin",
        title: "Fellow, Geriatric Psychiatry",
        paragraph1: "Dr. Agronin is an adult and geriatric psychiatrist and the author of the acclaimed books The End of Old Age: Living a Longer, More Purposeful Life (2018) and How We Age: A Doctor's Journey into the Heart of Growing Old (2011). He  is the Senior Vice President for Behavioral Health and Chief Medical Officer for the Memory and Research Center at Miami Jewish Hospital (MJH), now called MIND Institute. He is also an Affiliate Associate Professor of Psychiatry and Neurology at the University of Miami Miller School of Medicine. Dr. Agronin is a Distinguished Fellow of both the American Psychiatric Association and the AAGP and currently serves as President of AAGP. He is currently spearheading the creation of a new empathy-based care model called Miami Jewish EmpathiCare™ along with the first EmpathiCare-based village for individuals with Alzheimer's disease and other forms of dementia, on the campus of MJH.",
        paragraph2: "Senior Vice President for Behavioral Health for the Memory and Research Center at Miami Jewish Health",
        paragraph3: "Chief Medical Officer at MIND Institute",
        paragraph4: "Affiliate Associate Professor of Psychiatry and Neurology at the University of Miami Miller School of Medicine",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "5",
        name: "Dr. Christopher S. Ahmad",
        title: "Fellow, Orthopedics & Sports Medicine",
        paragraph1: "Dr. Ahmad has authored more than 200 articles and 50 book chapters related to knee, shoulder, elbow and sports medicine and has given greater than 300 lectures nationally, and internationally. He is the author of several sports medicine textbooks including “Pediatric and Adolescent Sports Injuries.” He has ongoing research in the areas of ACL injury prevention and screening, throwing related injury prevention and treatment, and surgical techniques for rotator cuff repair and shoulder instability.",
        paragraph2: "Professor of Clinical Orthopaedic Surgery at the Columbia University College of Physicians and Surgeons",
        paragraph3: "Chief of Sports Medicine and Director, Biomechanics Research at the Center for Orthopaedic Research at Columbia University",
        paragraph4: "Head Team Physician at the New York Yankees",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "6",
        name: "Dr. Kim Amrami",
        title: "Fellow, Radiology",
        paragraph1: "Dr. Amrami is a fellow of the American College of Radiology, the International Society of Magnetic Resonance in Medicine and the Society for Advanced Body Imaging. Her research interests center on Musculoskeletal MRI, with emphasis on MR imaging of peripheral nerve, hand and wrist imaging and high field MR imaging. Dr. Amrami also serves as a Special Government Employee for the FDA Center for Devices and Radiologic Health in addition to participating in review panels for the NIH and VA.",
        paragraph2: "Vice Chair, Department of Radiology at Mayo Clinic",
        paragraph3: "Professor of Radiology at the Mayo Clinic College of Medicine & Science",
        paragraph4: "Consultant, Department of Radiology and Department of Neurological Surgery at Mayo Clinic",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "7",
        name: "Dr. Louis J. Aronne",
        title: "Fellow, Obesity & Metabolic Health",
        paragraph1: "Dr. Aronne is a leading authority on obesity and its treatment. He is a founder and past chairman of the American Board of Obesity Medicine and a past president of The Obesity Society. He is a founder, board member, and senior scientific advisor for Intellihealth, a cloud-based weight management system for healthcare providers. Dr. Aronne has been an investigator on more than 50 trials of obesity treatment modalities including medications, devices, and diets.",
        paragraph2: "Sanford I. Weill Professor of Metabolic Research at Weill Cornell Medical College",
        paragraph3: "Director, Comprehensive Weight Control Center at the Weill Center for Metabolic Health",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "8",
        name: "Dr. Nir Barzilai",
        title: "Fellow, Aging & Genetics",
        paragraph1: "Dr. Barzilai is a chaired Professor of Medicine and Genetics, Director of the largest center to study the Biology of Aging, and the principal investigator of the Einstein Nathan Shock Center and the Glenn Center. Dr. Barzilai studies families of centenarians that have provided genetic/biological insights on the protection against aging. Dr. Barzilai is on the Board of AFAR and serves as its scientific director. He is a founding member of the Academy for Lifespan and Healthspan, the Longevity Biotech Association, Longevity Medicine Society, and co-founded CohBar and Life Biosciences.",
        paragraph2: "Professor of Medicine and Genetics at the Albert Einstein College of Medicine",
        paragraph3: "Ingeborg and Ira Leon Rennert Chair in Aging Research",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "9",
        name: "Dr. Brent A. Bauer",
        title: "Fellow, Integrative Medicine",
        paragraph1: "Dr. Bauer is board-certified in Internal Medicine, a Professor of Medicine and has been on staff at Mayo Clinic for 29 years. His main research interest has been the scientific evaluation of Integrative Medicine therapies. He founded the Integrative Medicine Program at Mayo Clinic, as well as Mayo Clinic's first spa, Rejuvenate. He is also the former Medical Director of the Well Living Lab, which explores the impact of the indoor environment on wellness.",
        paragraph2: "Vice Chair for Research, Division of General Internal Medicine, Department of Internal Medicine at Mayo Clinic",
        paragraph3: "Consultant (Joint Appointment), Division of Geriatric Medicine and Gerontology, Department of Internal Medicine at Mayo Clinic",
        paragraph4: "Professor of Medicine at the Mayo Clinic College of Medicine & Science",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "10",
        name: "Dr. Sharon A. Brangman",
        title: "Fellow, Geriatrics",
        paragraph1: "Dr. Brangman is board-certified in internal medicine, geriatric medicine, and hospice and palliative medicine. Prior to her current appointment at SUNY Upstate Medical University, she had been the Division Chief of Geriatrics for 20 years. In addition, Dr. Brangman is Medical Director of the Transitional Care Unit on the Upstate Community Campus, and is Medical Director of Greenpoint/The Hearth Senior Living Communities in Syracuse, New York.",
        paragraph2: "Distinguished Service Professor and Inaugural Chair, Department of Geriatrics at SUNY Upstate Medical University",
        paragraph3: "Director, Center of Excellence for Alzheimer's Disease at SUNY Upstate Medical University",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "11",
        name: "Dr. Lisa R. Callahan",
        title: "Fellow, Sports Medicine",
        paragraph1: "Dr. Callahan currently serves as Chief Medical Officer and Senior Vice President of Player Care at Madison Square Garden Sports, where she oversees the care of the Knicks (NBA), Rangers (NHL), Westchester Knicks (NBA D-League) and the Hartford Wolf Pack (AHL). She served two terms as President of the NBA Team Physicians Association, and has been a team physician for USA Basketball National Teams since 2014, working with both the men's and women's gold-medal winning teams in the 2016 Olympic Games in Rio. Since 1994, she has been on staff at HSS, where she co-founded the Women's Sports Medicine Center, the first of its kind in the country.",
        paragraph2: "Chief Medical Officer and Senior Vice President of Player Care at Madison Square Garden Sports",
        paragraph3: "Associate Professor, Department of Medicine at Weill Cornell Medical College",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "12",
        name: "Dr. Arthur L. Caplan",
        title: "Fellow, Medical Ethics",
        paragraph1: "Prior to NYU, Dr. Caplan was the Sidney D. Caplan Professor of Bioethics at the University of Pennsylvania Perelman School of Medicine in Philadelphia, where he created the Center for Bioethics and the Department of Medical Ethics. He has served as the Chair of the National Cancer Institute Biobanking Ethics Working Group, Chair of the Advisory Committee to the United Nations on Human Cloning; and Chair of the Advisory Committee to the Department of Health and Human Services on Blood Safety and Availability. Dr. Caplan is also the Co-Director of the Joint Council of Europe/United Nations Study on Trafficking in Organs and Body Parts.",
        paragraph2: "Drs. William F. and Virginia Connolly Mitty Professor of the Division of Medical Ethics at NYU School of Medicine",
        paragraph3: "Founding Head of the Division of Medical Ethics at NYU School of Medicine",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "13",
        name: "Dr. Mitchell S. Elkind",
        title: "Fellow, Vascular Neurology",
        paragraph1: "Dr. Elkind's research focuses on stroke prevention, inflammatory and infectious biomarkers in stroke risk prediction, atrial cardiopathy, immune therapy for acute stroke, and vascular causes of cognitive aging. Dr. Elkind is the Principal Investigator of several independent investigator awards from NIH/NINDS, including the ARCADIA trial,  the Northern Manhattan Study (NOMAS), the Neuroprotection with Statin Therapy for Acute Recovery Trial (NeuSTART), and the Levels of Inflammatory Markers in Treatment of Stroke (LIMITS) study. Dr. Elkind was President of the American Heart Association 2020-2021.",
        paragraph2: "Professor of Neurology and Epidemiology at Columbia University",
        paragraph3: "Chief Clinical Science Officer at the American Heart Association",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "14",
        name: "Dr. John G. Golfinos",
        title: "Fellow, Neurosurgery",
        paragraph1: "Dr. Golfinos is a national and international expert on the treatment of vestibular schwannomas and neurofibromatosis type 2. He founded the Gamma Knife Radiosurgery unit at NYU, the first of its kind in New York City. His areas of research include the use of radiosurgery in the treatment of cerebral metastases and studies comparing the use of radiosurgery and surgery in the treatment of vestibular schwannomas. He is also the President of the North American Skull Base Society.",
        paragraph2: "Neurosurgeon-in-Chief at the NYU Langone Medical Center",
        paragraph3: "Chairman, Department of Neurosurgery at NYU Langone Health",
        paragraph4: "Joseph P. Ransohoff Professor and Chairman of Neurosurgery at the NYU Grossman School of Medicine",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "15",
        name: "Dr. Robert C. Green",
        title: "Fellow, Genetics",
        paragraph1: "Dr. Green's empirical research and policy development is accelerating the implementation of genomic and precision medicine. His work has established the safety and feasibility of disclosing various forms of genetic risk information, assessed the impact of whole genome sequencing in primary care, created the concept of aggregate penetrance of genomic variants in a prospective population cohort and provided early data on the clinical utility and cost-effectiveness of genomic sequencing in healthy adults. Dr. Green established the world's first academically-affiliated, family-oriented Preventive Genomics Clinic in Boston. In 2017, he co-founded the nationwide tele-genetics company Genome Medical.",
        paragraph2: "Professor of Medicine (Genetics) at Mass General Brigham and Harvard Medical School",
        paragraph3: "Director at Genomes2People Research / Preventive Genomics Service / Precision Population Health Initiative",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "16",
        name: "Dr. Robin Carhart-Harris",
        title: "Fellow, Neuropsycology/ Psychedelics Research",
        paragraph1: "A renowned leader in neuroscience research, Dr. Carhart-Harris is the Ralph Metzner Distinguished Professor of Neurology and Psychiatry at UCSF. He is also the Founding Director of the UCSF Neuroscape Psychedelics Division. Previously, he led the Centre for Psychedelic Research at Imperial College London. He has designed a number of functional brain imaging studies with psilocybin, LSD, MDMA, and DMT and completed multiple clinical trials of psilocybin for depression. Dr. Carhart-Harris is one of the most cited researchers in the world in psychedelic science, helping to elucidate the neural and biochemical underpinnings of psychedelic molecules and their therapeutic effects.",
        paragraph2: "Ralph Metzner Distinguished Professor of Neurology and Psychiatry at the University of California, San Francisco (UCSF)",
        paragraph3: "Founding Director, UCSF Neuroscape Psychedelics Division",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "17",
        name: "Dr. Joseph M. Hoxworth",
        title: "Fellow, Neuroradiology",
        paragraph1: "Dr. Hoxworth's primary research focus within the discipline of Neuroradiology is head & neck radiology with a particular emphasis on sinonasal imaging and head & neck cancer. In a separate area of interest, he and his colleagues developed a novel imaging method known as “digital subtraction myelography” for the detection of spinal cerebrospinal fluid (CSF) leaks, a technique which has subsequently become widely adopted for clinical use and helped to uncover the role of CSF-venous fistulae in this disorder.",
        paragraph2: "Neuroradiologist",
        paragraph3: "Chair, Division of Neuroradiology at Mayo Clinic",
        paragraph4: "Vice Chair, Department of Radiology at Mayo Clinic",
        paragraph5: "Associate Professor of Radiology at the Mayo Clinic College of Medicine & Science",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "18",
        name: "Dr. Michelle Johnson",
        title: "Fellow, Cardiology & Health Equity",
        paragraph1: "Dr. Johnson is the Vice Chair of Health Equity and the Clinical Director of Cardiology at Memorial Sloan Kettering Cancer Center. Her extensive leadership experience in academic medicine includes developing clinical service lines, as well as designing policies and procedures to ensure quality and safety while optimizing efficiencies. She is also engaged in sourcing and screening cutting edge technologies for innovation in cardio-oncology. She is responsible for strategic plans for physician recruitment and retention. She serves on the board of The Association of Black Cardiologists.",
        paragraph2: "Vice Chair of Health Equity, Department of Medicine and Clinical Director of Cardiology, at Memorial Sloan Kettering Cancer Center",
        paragraph3: "Attending Physician at the Memorial Hospital for Cancer and Allied Diseases",
        paragraph4: "Assistant Professor of Clinical Medicine at Weill Cornell Medical College",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "19",
        name: "Dr. Susan Lynch",
        title: "Fellow, Microbiome Medicine",
        paragraph1: "Dr. Susan Lynch's  research at the Lynch Lab focuses on the role of microbiomes in the origins and chronicity of inflammatory diseases. Leveraging principles of microbial physiology with ecological theory, her research program strives to understand human microbiome genesis, establishment and influence on human immunity. Studies integrate clinical outcomes with large multi-dimensional human microbiome datasets. Leveraging observations made in human populations to inform model systems aimed at deconstructing these complex interactions, researchers at the Lynch Lab strive to determine microbial-derived mechanisms that promote immune function and programming that contribute to the origins of childhood asthma and to established inflammation in inflammatory bowel disease.",
        paragraph2: "Director, Benioff Center for Microbiome Medicine",
        paragraph3: "Associate Director, Microbiome in Inflammatory Bowel Disease Program",
        paragraph4: "Professor of Medicine, UCSF",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "20",
        name: "Dr. Jennifer H. Mieres",
        title: "Fellow, Cardiology & Health Equity",
        paragraph1: "Dr. Mieres' clinical focus and research are centered on the elimination of health and gender disparities and cardiovascular disease in women. Under Dr. Mieres' leadership, Northwell Health has been recognized as a top health system for diversity, equity and inclusion, most notably by Diversity Inc. as a Top 10 healthcare institution for a measurable commitment to health care justice. Northwell Health has been in the top 10 list for nine consecutive years and was recognized as number one in 2020 and 2021.",
        paragraph2: "Professor of Cardiology and Associate Dean of Faculty Affairs at the Zucker School of Medicine at Hofstra/Northwell",
        paragraph3: "Senior Vice President, Center for Equity of Care at Northwell Health",
        paragraph4: "Inaugural Chief Diversity and Inclusion Officer at Northwell Health",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "21",
        name: "Dr. Richard A. Miller",
        title: "Fellow, Aging Research",
        paragraph1: "Dr. Miller is a Professor of Pathology and Director of the Paul F. Glenn Center for Aging Research at the  University of Michigan. Dr. Miller is a past editor-in-chief of Aging Cell and has served as advisor for the American Federation for Aging Research and the National Institute on Aging. He is a Senior Scholar of the Ellison Medical Foundation, and a Fellow of the American Association for the Advancement of Science. He is the recipient of the Nathan Shock Award, the AlliedSignal Award, the Irving Wright Award, an award from the Glenn Foundation, and the Kleemeier Award for aging research. His research program includes ongoing studies of the mechanisms that link stress, nutrients, and hormones to delayed aging in mice, development of new approaches to slow aging and disease through drugs, early life dietary restriction, and targeted mutations.",
        paragraph2: "Professor of Pathology, Geriatrics Center at University of Michigan",
        paragraph3: "Director, University of Michigan's Paul F. Glenn Center for Aging Research",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "22",
        name: "Dr. Ernesto Pompeo Molmenti",
        title: "Fellow, Transplant Medicine",
        paragraph1: "At Northwell Health, Dr. Molmenti established the adult (2007) and pediatric (2016) kidney transplant programs, and founded the multi-disciplinary Division of Surgical Innovation across 24 hospitals, of which he is System Chief (2019). Northwell Health, in collaboration with i360medical, invested $2.5 million in the development of one of his surgical devices (2019). Dr. Molmenti is a named inventor / co-inventor in multiple patents/patent applications.",
        paragraph2: "System Chief, Surgical Innovation and Vice Chairman, Department of Surgery at North Shore University Hospital | Northwell Health",
        paragraph3: "Director, Kidney Transplantation at North Shore University Hospital | Northwell Health",
        paragraph4: "Professor, Departments of Surgery, Medicine, and Pediatrics at the Zucker School of Medicine at Hofstra / Northwell",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "23",
        name: "Dr. Lawrence C. Newman",
        title: "Fellow, Neurology",
        paragraph1: "In addition to being Atria's Director of Brain Health, Dr. Lawrence Newman is a Professor of Neurology at the NYU Langone School of Medicine. Prior to joining Atria, he served as the Director of the Division of Headache at NYU Langone Medical Center.",
        paragraph2: "Dr. Newman is Chair of the American Migraine Foundation, former President of the American Headache Society (AHS), currently serves on the Board of Directors of AHS, and previously served on the Board of Directors of the Headache Cooperative of New England. He is a Fellow of the American Headache Society and the American Academy of Neurology.",
        paragraph3: "Professor of Neurology at the NYU Grossman School of Medicine",
        paragraph4: "Chair, American Migraine Foundation",
        paragraph5: "Diplomat, Neurology, American Board of Psychiatry and Neurology",
        paragraph6: "Diplomat, Headache Medicine, United Council for Neurologic Subspecialties;",
        paragraph7: ""
    },
    {
        id: "24",
        name: "Prof. David Nutt",
        title: "Fellow, Neuropsychopharmacology",
        paragraph1: "Professor David Nutt is a psychiatrist and the Edmond J. Safra Professor of Neuropsychopharmacology in Imperial College London. He has been president of the European Brain Council, the BAP, BNA, and ECNP. He is currently Founding Chair of the charity DrugScience.org.uk. Professor Nutt has published 35 books and over 1,000 papers, including in Nature, Cell Lancet and New England Journal of Medicine. These define his many landmark contributions to psychopharmacology including GABA and noradrenaline receptor function in anxiety disorders, serotonin function in depression, endorphin and dopamine function in addiction and the neuroscience and clinical utility of psychedelics.",
        paragraph2: "Edmond J. Safra Professor of Neuropsychopharmacology at Imperial College London",
        paragraph3: "",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "25",
        name: "Dr. Mayowa Owolabi",
        title: "Fellow, Vascular Neurology",
        paragraph1: "Dr. Owolabi is the pioneer Regional Vice-President, World Federation of NeuroRehabilitation (Africa); African Regional Director, World Hypertension League, Foundation Co-Chair, African Stroke Organization and Rapporteur of the World Health Organization(WHO), Technical Advisory Committee on Non-Communicable Diseases (Research & Innovation). He is the Lead Co-Chair, WHO-World Stroke Organization (WSO) Lancet Commission on stroke. Dr. Owolabi is the winner of the 2021 WSO Global Award for Outstanding Contributions to Clinical Stroke Research. He has over 330 publications with over 79,100 citations and a Google Scholar h-index of 71. He has led many research studies SIREN - the largest study of stroke in Africa.",
        paragraph2: "Professor of Neurology at the University of Ibadan, Nigeria",
        paragraph3: "Pioneer Director, Center for Genomic and Precision Medicine at the University of Ibadan, Nigeria",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "26",
        name: "Dr. Ronald C. Petersen",
        title: "Fellow, Neurology & Alzheimer's",
        paragraph1: "Dr. Petersen has served on the National Advisory Council on Aging and the Board of Scientific Counselors of the National Institute on Aging, the Board of Directors of the national Alzheimer's Association, Chair of the Advisory Council on Research, Care and Services for the National Plan to Address Alzheimer's Disease and the World Dementia Council. Dr. Petersen is a recipient of the 2004 MetLife Award for Medical Research in Alzheimer's Disease, the 2005 Potamkin Prize for Research in Pick's, Alzheimer's and Related Disorders of the American Academy of Neurology.",
        paragraph2: "Professor of Neurology at the Mayo Clinic College of Medicine",
        paragraph3: "Cora Kanow Professor of Alzheimer's Disease Research at the Mayo Clinic College of Medicine & Science",
        paragraph4: "Director, Mayo Alzheimer's Disease Research Center at the Mayo Clinic College of Medicine & Science",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "27",
        name: "Dr. Caroline Poland",
        title: "Fellow, Trauma Informed Care Programs",
        paragraph1: "Caroline M. Poland is a Licensed Mental Health Counselor, Clinical Addictions Counselor, and a Nationally Certified Counselor, Clinical Trauma Professional, Compassion Fatigue Professional. She is also certified in EMDR therapy for those who experience distress around traumatic memories and Post Traumatic Stress Disorder. She is the creator of the Preferred Cognitive Styles and Decision Making Model, and a former Director of the Counseling Center at Taylor University. She is a member of the Board of Advisors for the Vaccine Education Project. She has presented over 160 invited seminars and talks nationally and internationally and has published extensively on incorporating psychological and cognitive models into health decision making.",
        paragraph2: "Founder and CEO, Poland and Associates Consulting",
        paragraph3: "Founder and Owner, Landmark Counseling",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "28",
        name: "Dr. Hollis G. Potter",
        title: "Fellow, Radiology",
        paragraph1: "Dr. Potter's current research interests lie in the use of quantitative MR imaging as a biomarker for assessment of early depletion of matrix from cartilage and fibrocartilage, as well as the reduction of susceptibility artifact around orthopaedic hardware. Most recently, she is the recipient of the 2022 Gold Medal Award from the International Society of Magnetic Resonance in Medicine. Dr. Potter is a Co-Founder of Imagen Technologies, a startup company which uses artificial intelligence to interpret diagnostic images.",
        paragraph2: "Chairman, Department of Radiology and Imaging and Coleman Chair in MRI Research at the Hospital for Special Surgery",
        paragraph3: "Director, Hospital for Special Surgery MRI Laboratory",
        paragraph4: "Professor of Radiology at Weill Cornell Medical College",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "29",
        name: "Dr. Scott Rodeo",
        title: "Fellow, Sports Medicine",
        paragraph1: "Dr. Rodeo's clinical practice involves orthopaedic sports medicine, with specialty interest in complex knee reconstruction (ligament, meniscus and cartilage surgery), tendon repair in the shoulder and other joints, and shoulder instability. He runs a translational research laboratory program investigating the cellular and molecular mechanisms of soft tissue repair. Dr. Rodeo is Head Team Physician for the New York Giants Football Team, and he served as a Team Physician for the United States Olympic Team in 2004, 2008, and 2012.",
        paragraph2: "Professor of Orthopaedic Surgery at Weill Cornell Medical College",
        paragraph3: "Attending Surgeon at NewYork-Presbyterian Hospital and Hospital for Special Surgery",
        paragraph4: "Co-Chief Emeritus of the Sports Medicine and Shoulder Service, Vice Chair of Orthopaedic Research, and Co-Director of the Orthopaedic Soft Tissue Research Program at Hospital for Special Surgery",
        paragraph5: "Director of the Center for Regenerative Medicine at the Hospital for Special Surgery",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "31",
        name: "Dr. Robert Rountree",
        title: "Fellow, Integrative Medicine",
        paragraph1: "Dr. Rountree began his career at Wellspring, Partners in Health, one of the first holistic healthcare centers in the U.S. Since January 2002, he has been the Medical Director of Boulder Wellcare, a private practice specializing in integrative, personalized medicine. In addition to his medical practice, he is a member of the core faculty for the Institute for Functional Medicine and the Chief Medical Advisor for Thorne HealthTech, a world leader in the production of pure, high-quality nutritional and botanical supplements. Dr. Rountree is the long-time clinical editor of the journal, Alternative and Complementary Medicine (recently renamed Integrative and Complementary Medicine), published by Mary Ann Liebert.",
        paragraph2: "Owner and Medical Director at Boulder Wellcare",
        paragraph3: "Chief Medical Advisor at Thorne HealthTech",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "32",
        name: "Dr. William Salter",
        title: "Fellow, Cardiology",
        paragraph1: "Dr. Slater practices and teaches general cardiology, with particular expertise in cardiac arrhythmia management. He specializes in providing second opinions to patients with heart rhythm problems as well as those with coronary artery disease and heart valve disease. As a professor, he has been honored with the Teacher of the Year Award from NYU Langone's Department of Medicine three times, as well as the Teacher of the Year Award from the Leon H. Charney Division of Cardiology three times.",
        paragraph2: "Professor of Medicine at the NYU Grossman School of Medicine",
        paragraph3: "Director, Cardiac Consultation Service at NYU-Bellevue Hospital",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "33",
        name: "Dr. Amit Sood",
        title: "Fellow, Resilience/ Neuroscience",
        paragraph1: "Dr. Sood is internationally known for his work on stress management, resilience, wellbeing, mindfulness, and burnout. He is a former Professor of Medicine at Mayo Clinic, Director of the Mind-Body Medicine Initiative, and Carla J. Paonessa enterprise chair of student life and wellbeing. Dr. Sood's work has resulted in many resilience and wellbeing programs including Stress Management and Resiliency Training (SMART©), Resilient Option, Certified Resilience Trainer (CeRT) Course, Year of Healing, Immune Resilience, HappiGenius, and Zizo: Your Resilience Assistant. SMART has been tested in over thirty clinical trials and reaches approximately 250,000 participants each year. Dr. Sood has authored or co-authored over 80 peer-reviewed articles, editorials, book chapters, abstracts and letters. He developed the first Mayo Clinic iPhone app for meditation training. He has also authored multiple books including The Mayo Clinic Guide to Stress-Free Living, The Mayo Clinic Handbook for Happiness, Immerse: A 52-Week Course in Resilient Living, Mindfulness Redesigned for the Twenty-First Century, Stronger, SMART with Dr. Sood, 2021: Your Year of Healing, and That Makes Sense: Bite-sized resilience insights to lift your day.",
        paragraph2: "",
        paragraph3: "",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "34",
        name: "Dr. Matthew B. Stern",
        title: "Fellow, Parkinson's Diseases & Movement Disorders",
        paragraph1: "Dr. Stern co-founded Penn's Parkinson's Disease and Movement Disorders Center, which he helped build into one of the premier centers of its kind in the world. He is an inaugural member of Penn's Academy of Master Clinicians, and the University of Pennsylvania recently established the Howard Hurtig-Matthew Stern Professorship in Neurology to commemorate his contributions to Penn Medicine. Penn also established the Matthew B. Stern, M.D. Lectureship in Neurology in 2022. He is the founding director of the Philadelphia VA Parkinson's Disease Research, Education and Clinical Center and a Past President of the International Parkinson and Movement Disorder Society.",
        paragraph2: "Parker Family Professor Emeritus of Neurology at the Perelman School of Medicine at the University of Pennsylvania",
        paragraph3: "Director Emeritus of the Parkinson's Disease and Movement Disorders Center",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "35",
        name: "Dr. Keith Stewart",
        title: "Fellow, Cancer",
        paragraph1: "Dr. Stewart has served in several healthcare leadership roles across both research and clinical practice in Toronto and at the Mayo Clinic. He returned to Toronto from the Mayo Clinic where he most recently was Director of the Center for Individualized Medicine. Dr. Stewart's research and clinical practice is focused on the biology, genomics and treatment of Multiple Myeloma. He currently serves as a non-executive board member of Genomics England.",
        paragraph2: "Vice President, Cancer at University Health Network",
        paragraph3: "Director, Princess Margaret Cancer Program at University Health Network",
        paragraph4: "Regional Vice-President at Ontario Health (Cancer Care Ontario)",
        paragraph5: "Richard H. Clark Chair in Cancer Medicine at University of Toronto",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "36",
        name: "Dr. Marcel R. M. van den Brink",
        title: "Fellow, Cancer & Immunology",
        paragraph1: "As Head of the Division of Hematologic Malignancies and an Attending Physician of the Adult Bone Marrow Transplantation Service, Dr. van den Brink sees patients undergoing a bone marrow transplantation at Memorial Sloan Kettering Cancer Center. He studies novel strategies to improve immune therapies for cancer patients with a special emphasis on the role of the intestinal microbiome in (patho)physiology and therapy, Chimeric Antigen Receptor T cell therapy, and regeneration of thymic function to improve T cell immunity.",
        paragraph2: "Alan Houghton Professor in Immunology and Head, Division of Hematologic Oncology at Memorial Sloan Kettering Cancer Center",
        paragraph3: "Member, Memorial Sloan Kettering Cancer Center",
        paragraph4: "Professor of Medicine and Immunology at Weill Cornell Medical College",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "37",
        name: "Dr. Mark Verstegen",
        title: "Fellow, Human Performance",
        paragraph1: "Mark Verstegen, one of the world's most innovative human performance experts, pioneered the concept of integrated performance training, which he's brought to the world's top athletes, teams, the United States military, and over thirty Fortune 100 companies. As the president and founder of EXOS, he leads more than 3,400 employees at 400 locations. He's also the author of six books, including 'Every Day Is Game Day' (2014), and has served as the Performance Director for the NFL Players Association for over 20 years.",
        paragraph2: "President and Founder at EXOS",
        paragraph3: "",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "38",
        name: "Dr. Michael G. Vitale",
        title: "Fellow, Orthopedics & Spine",
        paragraph1: "Dr. Vitale is Vice Chair for Quality and Strategy of the Department of Orthopedic Surgery at Columbia University Medical Center and the Chief of Pediatric Orthopedics for the New York Presbyterian Enterprise. As an internationally recognized expert in pediatric spine surgery, Dr. Vitale has been on the forefront of clinical innovation in this field. Performing more than 200 spinal operations per year, Dr. Vitale leverages specialized teams to drive quality, safety, and value. With over 250 published articles, Dr. Vitale has also been at the forefront of academic leadership and national governance in the field, serving as President of national organizations such as POSNA, IPOS, SP3, and PSF.",
        paragraph2: "Vice Chair, Quality and Strategy and Ana Lucia Professor of Orthopaedic Surgery at Columbia University Medical Center",
        paragraph3: "Chief of Pediatric Orthopedics at the New York Presbyterian Enterprise",
        paragraph4: "Director, Pediatric Spine and Scoliosis Service, New York Presbyterian Morgan Stanley Children's Hospital",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "39",
        name: "Dr. Phyllis Zee",
        title: "Fellow, Sleep Medicine",
        paragraph1: "As Director of the Center for Circadian and Sleep Medicine, Dr. Zee oversees an interdisciplinary program in basic and translational sleep and circadian rhythm research, and findings from her team have paved the way for innovative approaches, including several patents, to improve sleep and circadian health. She is the founder of the first circadian medicine clinic in the U.S. A central theme of her research program is understanding the role of circadian-sleep interactions on the expression and development of cardiometabolic and neurologic disorders.",
        paragraph2: "Benjamin and Virginia T. Boshes Professor in Neurology and Professor of Neurobiology at Northwestern University",
        paragraph3: "Director of the Center for Circadian and Sleep Medicine (CCSM) and Chief of the Division of Sleep Medicine at Northwestern University's Feinberg School of Medicine",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
    {
        id: "40",
        name: "Dr. Karen Zur",
        title: "Fellow, Speech Pathology & Otolaryngology",
        paragraph1: "An innovative laryngologist, Dr. Zur's expertise and advice is sought by speech-language pathologists and otolaryngologists around the globe. In 2020, she performed Israel's first laryngeal reinnervation surgery with an audience of adult and pediatric voice specialists. In December 2020, Dr. Zur was named Chief of the Division of Otolaryngology, serving as the first female chief within Children's Surgical Associates, Ltd. In Spring 2021, Dr. Zur was promoted to Professor within the Department of Otorhinolaryngology: Head & Neck Surgery at the Perelman School of Medicine at the University of Pennsylvania.",
        paragraph2: "Chief, Division of Otolaryngology; E. Mortimer Newlin Endowed Chair in Pediatric Otolaryngology and Human Communication; Director, Pediatric Voice Program; and Associate Director, Center for Pediatric Airway Disorders at Children's Hospital of Philadelphia",
        paragraph3: "Professor, Department of Otorhinolaryngology: Head & Neck Surgery at the Perelman School of Medicine at the University of Pennsylvania",
        paragraph4: "",
        paragraph5: "",
        paragraph6: "",
        paragraph7: ""
    },
]

export default fellowsData;